// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthControl.proto

package io.healthControl.CA.watchFit;

public interface ExerciseZoneResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExerciseZoneResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 fatBurnValue = 1;</code>
   */
  int getFatBurnValue();

  /**
   * <code>int32 cardioValue = 2;</code>
   */
  int getCardioValue();

  /**
   * <code>int32 peakValue = 3;</code>
   */
  int getPeakValue();
}
