// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthControl.proto

package io.healthControl.CA.watchFit;

public interface ExerciseZoneResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExerciseZoneResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fatBurnValue = 1;</code>
   */
  java.lang.String getFatBurnValue();
  /**
   * <code>string fatBurnValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getFatBurnValueBytes();

  /**
   * <code>string cardioValue = 2;</code>
   */
  java.lang.String getCardioValue();
  /**
   * <code>string cardioValue = 2;</code>
   */
  com.google.protobuf.ByteString
      getCardioValueBytes();

  /**
   * <code>string peakValue = 3;</code>
   */
  java.lang.String getPeakValue();
  /**
   * <code>string peakValue = 3;</code>
   */
  com.google.protobuf.ByteString
      getPeakValueBytes();
}
