// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthControl.proto

package io.healthControl.CA.watchFit;

public interface ExerciseZoneRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExerciseZoneRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>int32 restingHeartRate = 2;</code>
   */
  int getRestingHeartRate();
}
