// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthControl.proto

package io.healthControl.CA.watchFit;

public final class HealthControlgRPCProto {
  private HealthControlgRPCProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemperatureLevelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemperatureLevelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExerciseZoneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExerciseZoneRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExerciseZoneResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExerciseZoneResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023healthControl.proto\".\n\027TemperatureLeve" +
      "lRequest\022\023\n\013temperature\030\001 \001(\005\"e\n\023Tempera" +
      "tureResponse\022\030\n\020belowTemperature\030\001 \001(\005\022\032" +
      "\n\022averageTemperature\030\002 \001(\005\022\030\n\020aboveTempe" +
      "rature\030\003 \001(\005\"<\n\023ExerciseZoneRequest\022\013\n\003a" +
      "ge\030\001 \001(\005\022\030\n\020restingHeartRate\030\002 \001(\005\"T\n\024Ex" +
      "erciseZoneResponse\022\024\n\014fatBurnValue\030\001 \001(\005" +
      "\022\023\n\013cardioValue\030\002 \001(\005\022\021\n\tpeakValue\030\003 \001(\005" +
      "2\244\001\n\rHealthControl\022I\n\021TemperatureReport\022" +
      "\030.TemperatureLevelRequest\032\024.TemperatureR" +
      "esponse\"\000(\0010\001\022H\n\025ExerciseZoneRateLevel\022\024" +
      ".ExerciseZoneRequest\032\025.ExerciseZoneRespo" +
      "nse\"\0000\001B8\n\034io.healthControl.CA.watchFitB" +
      "\026HealthControlgRPCProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TemperatureLevelRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TemperatureLevelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemperatureLevelRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemperatureResponse_descriptor,
        new java.lang.String[] { "BelowTemperature", "AverageTemperature", "AboveTemperature", });
    internal_static_ExerciseZoneRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ExerciseZoneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExerciseZoneRequest_descriptor,
        new java.lang.String[] { "Age", "RestingHeartRate", });
    internal_static_ExerciseZoneResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ExerciseZoneResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExerciseZoneResponse_descriptor,
        new java.lang.String[] { "FatBurnValue", "CardioValue", "PeakValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
