// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthControl.proto

package io.healthControl.CA.watchFit;

public interface TemperatureLevelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TemperatureLevelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();
}
