// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthControl.proto

package io.healthControl.CA.watchFit;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 belowTemperature = 1;</code>
   */
  int getBelowTemperature();

  /**
   * <code>int32 averageTemperature = 2;</code>
   */
  int getAverageTemperature();

  /**
   * <code>int32 aboveTemperature = 3;</code>
   */
  int getAboveTemperature();
}
