// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthControl.proto

package io.healthControl.CA.watchFit;

/**
 * Protobuf type {@code TemperatureResponse}
 */
public  final class TemperatureResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TemperatureResponse)
    TemperatureResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TemperatureResponse.newBuilder() to construct.
  private TemperatureResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TemperatureResponse() {
    belowTemperature_ = 0;
    averageTemperature_ = 0;
    aboveTemperature_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TemperatureResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            belowTemperature_ = input.readInt32();
            break;
          }
          case 16: {

            averageTemperature_ = input.readInt32();
            break;
          }
          case 24: {

            aboveTemperature_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.healthControl.CA.watchFit.HealthControlgRPCProto.internal_static_TemperatureResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.healthControl.CA.watchFit.HealthControlgRPCProto.internal_static_TemperatureResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.healthControl.CA.watchFit.TemperatureResponse.class, io.healthControl.CA.watchFit.TemperatureResponse.Builder.class);
  }

  public static final int BELOWTEMPERATURE_FIELD_NUMBER = 1;
  private int belowTemperature_;
  /**
   * <code>int32 belowTemperature = 1;</code>
   */
  public int getBelowTemperature() {
    return belowTemperature_;
  }

  public static final int AVERAGETEMPERATURE_FIELD_NUMBER = 2;
  private int averageTemperature_;
  /**
   * <code>int32 averageTemperature = 2;</code>
   */
  public int getAverageTemperature() {
    return averageTemperature_;
  }

  public static final int ABOVETEMPERATURE_FIELD_NUMBER = 3;
  private int aboveTemperature_;
  /**
   * <code>int32 aboveTemperature = 3;</code>
   */
  public int getAboveTemperature() {
    return aboveTemperature_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (belowTemperature_ != 0) {
      output.writeInt32(1, belowTemperature_);
    }
    if (averageTemperature_ != 0) {
      output.writeInt32(2, averageTemperature_);
    }
    if (aboveTemperature_ != 0) {
      output.writeInt32(3, aboveTemperature_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (belowTemperature_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, belowTemperature_);
    }
    if (averageTemperature_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, averageTemperature_);
    }
    if (aboveTemperature_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, aboveTemperature_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.healthControl.CA.watchFit.TemperatureResponse)) {
      return super.equals(obj);
    }
    io.healthControl.CA.watchFit.TemperatureResponse other = (io.healthControl.CA.watchFit.TemperatureResponse) obj;

    boolean result = true;
    result = result && (getBelowTemperature()
        == other.getBelowTemperature());
    result = result && (getAverageTemperature()
        == other.getAverageTemperature());
    result = result && (getAboveTemperature()
        == other.getAboveTemperature());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BELOWTEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + getBelowTemperature();
    hash = (37 * hash) + AVERAGETEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + getAverageTemperature();
    hash = (37 * hash) + ABOVETEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + getAboveTemperature();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.healthControl.CA.watchFit.TemperatureResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.healthControl.CA.watchFit.TemperatureResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TemperatureResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TemperatureResponse)
      io.healthControl.CA.watchFit.TemperatureResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.healthControl.CA.watchFit.HealthControlgRPCProto.internal_static_TemperatureResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.healthControl.CA.watchFit.HealthControlgRPCProto.internal_static_TemperatureResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.healthControl.CA.watchFit.TemperatureResponse.class, io.healthControl.CA.watchFit.TemperatureResponse.Builder.class);
    }

    // Construct using io.healthControl.CA.watchFit.TemperatureResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      belowTemperature_ = 0;

      averageTemperature_ = 0;

      aboveTemperature_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.healthControl.CA.watchFit.HealthControlgRPCProto.internal_static_TemperatureResponse_descriptor;
    }

    @java.lang.Override
    public io.healthControl.CA.watchFit.TemperatureResponse getDefaultInstanceForType() {
      return io.healthControl.CA.watchFit.TemperatureResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.healthControl.CA.watchFit.TemperatureResponse build() {
      io.healthControl.CA.watchFit.TemperatureResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.healthControl.CA.watchFit.TemperatureResponse buildPartial() {
      io.healthControl.CA.watchFit.TemperatureResponse result = new io.healthControl.CA.watchFit.TemperatureResponse(this);
      result.belowTemperature_ = belowTemperature_;
      result.averageTemperature_ = averageTemperature_;
      result.aboveTemperature_ = aboveTemperature_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.healthControl.CA.watchFit.TemperatureResponse) {
        return mergeFrom((io.healthControl.CA.watchFit.TemperatureResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.healthControl.CA.watchFit.TemperatureResponse other) {
      if (other == io.healthControl.CA.watchFit.TemperatureResponse.getDefaultInstance()) return this;
      if (other.getBelowTemperature() != 0) {
        setBelowTemperature(other.getBelowTemperature());
      }
      if (other.getAverageTemperature() != 0) {
        setAverageTemperature(other.getAverageTemperature());
      }
      if (other.getAboveTemperature() != 0) {
        setAboveTemperature(other.getAboveTemperature());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.healthControl.CA.watchFit.TemperatureResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.healthControl.CA.watchFit.TemperatureResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int belowTemperature_ ;
    /**
     * <code>int32 belowTemperature = 1;</code>
     */
    public int getBelowTemperature() {
      return belowTemperature_;
    }
    /**
     * <code>int32 belowTemperature = 1;</code>
     */
    public Builder setBelowTemperature(int value) {
      
      belowTemperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 belowTemperature = 1;</code>
     */
    public Builder clearBelowTemperature() {
      
      belowTemperature_ = 0;
      onChanged();
      return this;
    }

    private int averageTemperature_ ;
    /**
     * <code>int32 averageTemperature = 2;</code>
     */
    public int getAverageTemperature() {
      return averageTemperature_;
    }
    /**
     * <code>int32 averageTemperature = 2;</code>
     */
    public Builder setAverageTemperature(int value) {
      
      averageTemperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 averageTemperature = 2;</code>
     */
    public Builder clearAverageTemperature() {
      
      averageTemperature_ = 0;
      onChanged();
      return this;
    }

    private int aboveTemperature_ ;
    /**
     * <code>int32 aboveTemperature = 3;</code>
     */
    public int getAboveTemperature() {
      return aboveTemperature_;
    }
    /**
     * <code>int32 aboveTemperature = 3;</code>
     */
    public Builder setAboveTemperature(int value) {
      
      aboveTemperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 aboveTemperature = 3;</code>
     */
    public Builder clearAboveTemperature() {
      
      aboveTemperature_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TemperatureResponse)
  }

  // @@protoc_insertion_point(class_scope:TemperatureResponse)
  private static final io.healthControl.CA.watchFit.TemperatureResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.healthControl.CA.watchFit.TemperatureResponse();
  }

  public static io.healthControl.CA.watchFit.TemperatureResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TemperatureResponse>
      PARSER = new com.google.protobuf.AbstractParser<TemperatureResponse>() {
    @java.lang.Override
    public TemperatureResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TemperatureResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TemperatureResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemperatureResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.healthControl.CA.watchFit.TemperatureResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

