// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

public interface BurnedCaloriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurnedCaloriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>int32 weight = 2;</code>
   */
  int getWeight();

  /**
   * <code>int32 height = 4;</code>
   */
  int getHeight();

  /**
   * <code>.BurnedCaloriesRequest.Gender gender = 3;</code>
   */
  int getGenderValue();
  /**
   * <code>.BurnedCaloriesRequest.Gender gender = 3;</code>
   */
  io.runningControl.CA.watchFit.BurnedCaloriesRequest.Gender getGender();

  /**
   * <code>double duration = 5;</code>
   */
  double getDuration();

  /**
   * <code>.BurnedCaloriesRequest.Activity activity = 6;</code>
   */
  int getActivityValue();
  /**
   * <code>.BurnedCaloriesRequest.Activity activity = 6;</code>
   */
  io.runningControl.CA.watchFit.BurnedCaloriesRequest.Activity getActivity();
}
