// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

public interface BurnedCaloriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurnedCaloriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 burnedCalories = 1;</code>
   */
  int getBurnedCalories();
}
