// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

public interface BurnedCaloriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurnedCaloriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>int32 weight = 2;</code>
   */
  int getWeight();

  /**
   * <code>int32 stepsTaken = 3;</code>
   */
  int getStepsTaken();
}
