// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

public interface BurnedCaloriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurnedCaloriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>int32 weight = 2;</code>
   */
  int getWeight();

  /**
   * <code>int32 height = 4;</code>
   */
  int getHeight();

  /**
   * <code>string gender = 3;</code>
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 3;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>double duration = 5;</code>
   */
  double getDuration();

  /**
   * <code>int32 activity = 6;</code>
   */
  int getActivity();
}
