// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

/**
 * <pre>
 * from server to client
 * </pre>
 *
 * Protobuf type {@code ExerciseTimeResponse}
 */
public  final class ExerciseTimeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ExerciseTimeResponse)
    ExerciseTimeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExerciseTimeResponse.newBuilder() to construct.
  private ExerciseTimeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExerciseTimeResponse() {
    exerciseTimeResponse_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExerciseTimeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            exerciseTimeResponse_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_ExerciseTimeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_ExerciseTimeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.runningControl.CA.watchFit.ExerciseTimeResponse.class, io.runningControl.CA.watchFit.ExerciseTimeResponse.Builder.class);
  }

  public static final int EXERCISETIMERESPONSE_FIELD_NUMBER = 1;
  private volatile java.lang.Object exerciseTimeResponse_;
  /**
   * <code>string exerciseTimeResponse = 1;</code>
   */
  public java.lang.String getExerciseTimeResponse() {
    java.lang.Object ref = exerciseTimeResponse_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exerciseTimeResponse_ = s;
      return s;
    }
  }
  /**
   * <code>string exerciseTimeResponse = 1;</code>
   */
  public com.google.protobuf.ByteString
      getExerciseTimeResponseBytes() {
    java.lang.Object ref = exerciseTimeResponse_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exerciseTimeResponse_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getExerciseTimeResponseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, exerciseTimeResponse_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getExerciseTimeResponseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, exerciseTimeResponse_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.runningControl.CA.watchFit.ExerciseTimeResponse)) {
      return super.equals(obj);
    }
    io.runningControl.CA.watchFit.ExerciseTimeResponse other = (io.runningControl.CA.watchFit.ExerciseTimeResponse) obj;

    boolean result = true;
    result = result && getExerciseTimeResponse()
        .equals(other.getExerciseTimeResponse());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXERCISETIMERESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + getExerciseTimeResponse().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.runningControl.CA.watchFit.ExerciseTimeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.runningControl.CA.watchFit.ExerciseTimeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * from server to client
   * </pre>
   *
   * Protobuf type {@code ExerciseTimeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ExerciseTimeResponse)
      io.runningControl.CA.watchFit.ExerciseTimeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_ExerciseTimeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_ExerciseTimeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.runningControl.CA.watchFit.ExerciseTimeResponse.class, io.runningControl.CA.watchFit.ExerciseTimeResponse.Builder.class);
    }

    // Construct using io.runningControl.CA.watchFit.ExerciseTimeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      exerciseTimeResponse_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_ExerciseTimeResponse_descriptor;
    }

    @java.lang.Override
    public io.runningControl.CA.watchFit.ExerciseTimeResponse getDefaultInstanceForType() {
      return io.runningControl.CA.watchFit.ExerciseTimeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.runningControl.CA.watchFit.ExerciseTimeResponse build() {
      io.runningControl.CA.watchFit.ExerciseTimeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.runningControl.CA.watchFit.ExerciseTimeResponse buildPartial() {
      io.runningControl.CA.watchFit.ExerciseTimeResponse result = new io.runningControl.CA.watchFit.ExerciseTimeResponse(this);
      result.exerciseTimeResponse_ = exerciseTimeResponse_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.runningControl.CA.watchFit.ExerciseTimeResponse) {
        return mergeFrom((io.runningControl.CA.watchFit.ExerciseTimeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.runningControl.CA.watchFit.ExerciseTimeResponse other) {
      if (other == io.runningControl.CA.watchFit.ExerciseTimeResponse.getDefaultInstance()) return this;
      if (!other.getExerciseTimeResponse().isEmpty()) {
        exerciseTimeResponse_ = other.exerciseTimeResponse_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.runningControl.CA.watchFit.ExerciseTimeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.runningControl.CA.watchFit.ExerciseTimeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object exerciseTimeResponse_ = "";
    /**
     * <code>string exerciseTimeResponse = 1;</code>
     */
    public java.lang.String getExerciseTimeResponse() {
      java.lang.Object ref = exerciseTimeResponse_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exerciseTimeResponse_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exerciseTimeResponse = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExerciseTimeResponseBytes() {
      java.lang.Object ref = exerciseTimeResponse_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exerciseTimeResponse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exerciseTimeResponse = 1;</code>
     */
    public Builder setExerciseTimeResponse(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exerciseTimeResponse_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exerciseTimeResponse = 1;</code>
     */
    public Builder clearExerciseTimeResponse() {
      
      exerciseTimeResponse_ = getDefaultInstance().getExerciseTimeResponse();
      onChanged();
      return this;
    }
    /**
     * <code>string exerciseTimeResponse = 1;</code>
     */
    public Builder setExerciseTimeResponseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exerciseTimeResponse_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ExerciseTimeResponse)
  }

  // @@protoc_insertion_point(class_scope:ExerciseTimeResponse)
  private static final io.runningControl.CA.watchFit.ExerciseTimeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.runningControl.CA.watchFit.ExerciseTimeResponse();
  }

  public static io.runningControl.CA.watchFit.ExerciseTimeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExerciseTimeResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExerciseTimeResponse>() {
    @java.lang.Override
    public ExerciseTimeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExerciseTimeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExerciseTimeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExerciseTimeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.runningControl.CA.watchFit.ExerciseTimeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

