// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

public interface ExerciseTimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExerciseTimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool exerciseTimeSignal = 1;</code>
   */
  boolean getExerciseTimeSignal();
}
