// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

public interface ExerciseTimeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExerciseTimeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exerciseTimeResponse = 1;</code>
   */
  java.lang.String getExerciseTimeResponse();
  /**
   * <code>string exerciseTimeResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getExerciseTimeResponseBytes();
}
