// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

public interface RestHeartRateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RestHeartRateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string restHeartLevelResponse = 1;</code>
   */
  java.lang.String getRestHeartLevelResponse();
  /**
   * <code>string restHeartLevelResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getRestHeartLevelResponseBytes();
}
