// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

/**
 * Protobuf type {@code RestHeartRateRequest}
 */
public  final class RestHeartRateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RestHeartRateRequest)
    RestHeartRateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RestHeartRateRequest.newBuilder() to construct.
  private RestHeartRateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RestHeartRateRequest() {
    restHeartLevel_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RestHeartRateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            restHeartLevel_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_RestHeartRateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_RestHeartRateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.runningControl.CA.watchFit.RestHeartRateRequest.class, io.runningControl.CA.watchFit.RestHeartRateRequest.Builder.class);
  }

  public static final int RESTHEARTLEVEL_FIELD_NUMBER = 1;
  private int restHeartLevel_;
  /**
   * <code>int32 restHeartLevel = 1;</code>
   */
  public int getRestHeartLevel() {
    return restHeartLevel_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (restHeartLevel_ != 0) {
      output.writeInt32(1, restHeartLevel_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (restHeartLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, restHeartLevel_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.runningControl.CA.watchFit.RestHeartRateRequest)) {
      return super.equals(obj);
    }
    io.runningControl.CA.watchFit.RestHeartRateRequest other = (io.runningControl.CA.watchFit.RestHeartRateRequest) obj;

    boolean result = true;
    result = result && (getRestHeartLevel()
        == other.getRestHeartLevel());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESTHEARTLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getRestHeartLevel();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.runningControl.CA.watchFit.RestHeartRateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.runningControl.CA.watchFit.RestHeartRateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RestHeartRateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RestHeartRateRequest)
      io.runningControl.CA.watchFit.RestHeartRateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_RestHeartRateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_RestHeartRateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.runningControl.CA.watchFit.RestHeartRateRequest.class, io.runningControl.CA.watchFit.RestHeartRateRequest.Builder.class);
    }

    // Construct using io.runningControl.CA.watchFit.RestHeartRateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      restHeartLevel_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.runningControl.CA.watchFit.RunningControlgRPCProto.internal_static_RestHeartRateRequest_descriptor;
    }

    @java.lang.Override
    public io.runningControl.CA.watchFit.RestHeartRateRequest getDefaultInstanceForType() {
      return io.runningControl.CA.watchFit.RestHeartRateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.runningControl.CA.watchFit.RestHeartRateRequest build() {
      io.runningControl.CA.watchFit.RestHeartRateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.runningControl.CA.watchFit.RestHeartRateRequest buildPartial() {
      io.runningControl.CA.watchFit.RestHeartRateRequest result = new io.runningControl.CA.watchFit.RestHeartRateRequest(this);
      result.restHeartLevel_ = restHeartLevel_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.runningControl.CA.watchFit.RestHeartRateRequest) {
        return mergeFrom((io.runningControl.CA.watchFit.RestHeartRateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.runningControl.CA.watchFit.RestHeartRateRequest other) {
      if (other == io.runningControl.CA.watchFit.RestHeartRateRequest.getDefaultInstance()) return this;
      if (other.getRestHeartLevel() != 0) {
        setRestHeartLevel(other.getRestHeartLevel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.runningControl.CA.watchFit.RestHeartRateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.runningControl.CA.watchFit.RestHeartRateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int restHeartLevel_ ;
    /**
     * <code>int32 restHeartLevel = 1;</code>
     */
    public int getRestHeartLevel() {
      return restHeartLevel_;
    }
    /**
     * <code>int32 restHeartLevel = 1;</code>
     */
    public Builder setRestHeartLevel(int value) {
      
      restHeartLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 restHeartLevel = 1;</code>
     */
    public Builder clearRestHeartLevel() {
      
      restHeartLevel_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RestHeartRateRequest)
  }

  // @@protoc_insertion_point(class_scope:RestHeartRateRequest)
  private static final io.runningControl.CA.watchFit.RestHeartRateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.runningControl.CA.watchFit.RestHeartRateRequest();
  }

  public static io.runningControl.CA.watchFit.RestHeartRateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RestHeartRateRequest>
      PARSER = new com.google.protobuf.AbstractParser<RestHeartRateRequest>() {
    @java.lang.Override
    public RestHeartRateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RestHeartRateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RestHeartRateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RestHeartRateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.runningControl.CA.watchFit.RestHeartRateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

