// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runningControl.proto

package io.runningControl.CA.watchFit;

public interface RestHeartRateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RestHeartRateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 restHeartLevel = 1;</code>
   */
  int getRestHeartLevel();
}
